version: "3.8"

services:
  mysqldb:
    image: mysql/mysql-server:8.0.30
    environment:
      - MYSQL_ROOT_PASSWORD=o
      - MYSQL_DATABASE=sensor
    ports:
      - 3307:3307
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3307/mydatabase?useSSL=false",
        "spring.datasource.username" : "thcode",
        "spring.datasource.password" : "o",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.properties.hibernate.engine" : "org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2

volumes:
  db: